### PR TITLE
scroll_derive: support reference

### LINKED ISSUE #83: Pwrite deriving fails with "unparseable tokens" with struct containing lifetimes?
Consider this structure:
```rust
#[derive(Pwrite)]
pub struct SymbolTable<'a> {
    symbols: &'a [u8],
}
```
(extracted from Goblin codebase)

This induces `proc-macro derive produced unparseable tokens`, on rustc 1.68.1.

I don't know what happens here.

### PR DESCRIPTION
**Pull request by Grvzard**
Closes #83

### CODE REVIEW

File: scroll_derive/src/lib.rs [hunk 1]
```diff
@@ -128,6 +128,14 @@ fn impl_pwrite_field(ident: &proc_macro2::TokenStream, ty: &syn::Type) -> proc_m
             _ => panic!("Pwrite derive with bad array constexpr"),
         },
         syn::Type::Group(group) => impl_pwrite_field(ident, &group.elem),
+        syn::Type::Reference(reference) => match *reference.elem {
+            syn::Type::Slice(_) => quote! {
+                dst.gwrite_with(self.#ident, offset, ())?
```
Comment (m4b) [inline scroll_derive/src/lib.rs:133]: why is a `()` ctx passed here?

File: scroll_derive/tests/tests.rs [hunk 2]
```diff
@@ -211,3 +211,24 @@ fn test_newtype() {
...
+
+#[test]
+fn test_reference() {
+    let inner = Data10I(255, 1);
+    let data = Data10 {
+        inner: &inner,
+        name: b"name",
+    };
+    let mut bytes = vec![0; 32];
+    assert_eq!(bytes.pwrite_with(&data, 0, LE).unwrap(), 7);
```
Comment (m4b) [inline scroll_derive/tests/tests.rs:232]: i'm surprised you can pass a `&data` reference to `pwrite_with` here, instead of just `data`

File: scroll_derive/src/lib.rs [hunk 3]
```diff
@@ -166,32 +174,38 @@ fn impl_try_into_ctx(
...
-                quote! {
+                Some(quote! {
                     #ident : ::scroll::ctx::TryIntoCtx<::scroll::Endian>,
                     ::scroll::Error: ::std::convert::From<<#ident as ::scroll::ctx::TryIntoCtx<::scroll::Endian>>::Error>,
                     <#ident as ::scroll::ctx::TryIntoCtx<::scroll::Endian>>::Error: ::std::convert::From<scroll::Error>
-                }
+                })
             },
-            p => quote! { #p }
+            syn::GenericParam::Lifetime(_) => None,
```
Comment (m4b) [inline scroll_derive/src/lib.rs:207]: not clear to me why this branch is `None` here

File: scroll_derive/Cargo.toml [hunk 4]
```diff
@@ -20,5 +20,5 @@ quote = "1"
 syn = "2"
 
 [dev-dependencies.scroll]
-version = "0.11"
+version = "0.12"
```
Comment (m4b) [inline scroll_derive/Cargo.toml:23]: thank you :)

**Review by m4b — APPROVED** [review]
My only question is about the `()` ctx; otherwise this looks great, thank you for looking into this and providing what appears to be a fix for this bug!

and thank you for adding the test!

File: scroll_derive/src/lib.rs (hunk 1 above)
Comment (Grvzard) [reply scroll_derive/src/lib.rs:133]: refer https://github.com/m4b/scroll/blob/3cffc5a2a1eaf4c7d698f3ffba2509523ece1875/src/ctx.rs#L713-L716

File: scroll_derive/src/lib.rs [hunk 5]
```diff
@@ -166,32 +174,38 @@ fn impl_try_into_ctx(
...
-                }
+                })
             },
-            p => quote! { #p }
-        });
-        quote! { where #( #gi ),* }
+            syn::GenericParam::Lifetime(_) => None,
+            p => Some(quote! { #p }),
+        }).collect();
+        if !gi.is_empty() {
```
[the remark this answers is not in the document]
Comment (Grvzard) [reply scroll_derive/src/lib.rs:189]: no, this one doesn't matter here. a dangling `where` clause will be ignored by rust. I did more processing here just to make the generated token clearer.

File: scroll_derive/src/lib.rs (hunk 3 above)
Comment (Grvzard) [reply scroll_derive/src/lib.rs:207]: actually 'the heart of the fix' is here.
the prevoius code doesn't process lifetime properly, which will generates tokens like
```
impl<'b> ... for ... 
where
    ... : ... ,
    'b
    ^^ invalid syntax
```

Comment (m4b) [reply scroll_derive/src/lib.rs:207]: i see, thank you for clarifying!

File: scroll_derive/tests/tests.rs (hunk 2 above)
Comment (Grvzard) [reply scroll_derive/tests/tests.rs:232]: the derivation of `Pwrite` will also generates a Pwrite impl for  `&Data`. that's not my credit :)

File: scroll_derive/src/lib.rs (hunk 1 above)
Comment (m4b) [reply scroll_derive/src/lib.rs:133]: :sweat_smile: haha yes i forgot `pwrite` for `&[u8]` has no ctx, though that is a bit quirky/assymetric, as it's `pread` has a usize ctx (e.g., how many things to read). r

**Review by m4b — APPROVED** [review]
thank you so much for fixing this!

**Comment by m4b** [comment]
Somewhat related, and wondering out loud, I hope there aren't similar bugs in the Cread derive code, as I think it is probably large copy pasted from the Pread derive code? anyway, great work and thanks for this fix, do you want a minor patch release for scroll_derive? if it's urgent i can release it now

**Comment by Grvzard** [comment]
> in the Cread derive code

i can investigate more and propose a PR later.

> do you want a minor patch release for scroll_derive

nope, it's okay. thanks though.

**Comment by m4b** [comment]
@Grvzard sorry for delay, released in 0.12.1
